### ISSUE TITLE
issue about config 

### ISSUE THREAD

**Issue by longyangqi** [ranandalon/mtl#3]
Thank you for sharing the code!
I have a question about the config/user_config, do you have another config file?
could you show an example for the config/user_config file?
or give an instruction for how to use the  config/user_config module?

Thanks!

**Comment by fuxiao567** [comment]
> Thank you for sharing the code!
> I have a question about the config/user_config, do you have another config file?
> could you show an example for the config/user_config file?
> or give an instruction for how to use the config/user_config module?
> 
> Thanks!

Do you have config.py now? Thank you!

**Comment by longyangqi** [comment]
Sorry, I do not work on that currently, and I can hardly remember that ... perhaps not

2019-12-30 21:10:43fuxiao567 <notifications@github.com>写道：

Thank you for sharing the code!
I have a question about the config/user_config, do you have another config file?
could you show an example for the config/user_config file?
or give an instruction for how to use the config/user_config module?

Thanks!

Do you have config.py now? Thank you!
